In [1]:
import os
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array

In [2]:
def get_model():
    global model
    model = load_model('model.h5')
    print("Model loaded!")

In [3]:
get_model()

Model loaded!


In [4]:
def load_image(img_path):

    img = image.load_img(img_path, target_size=(224, 224))
    img_tensor = image.img_to_array(img)                    # (height, width, channels)
    img_tensor = np.expand_dims(img_tensor, axis=0)         # (1, height, width, channels), add a dimension because the model expects this shape: (batch_size, height, width, channels)
    img_tensor /= 255.                                      # imshow expects values in the range [0, 1]

    return img_tensor

In [5]:
def prediction(img_path):
    new_image = load_image(img_path)
    
    pred = model.predict(new_image)
    
    print(pred)
    
    labels=np.array(pred)
    labels[labels>=0.6]=1
    labels[labels<0.6]=0
    
    print(labels)
    final=np.array(labels)
    
    if final[0][0]==1:
        return "Bad"
    else:
        return "Good"

In [6]:
prediction(r'D:/project1/dataset/test/bad (75)k.jpeg')

[[0.9938259  0.00617412]]
[[1. 0.]]


'Bad'

In [7]:
print(prediction(r'D:/project1/dataset/test/good (361)k.jpeg'))                                #significance of r"

[[1.8272604e-04 9.9981731e-01]]
[[0. 1.]]
Good


In [8]:
product = prediction(r'D:/project1/dataset/test/bad (25)k.jpeg')                                                                        #it will accept image directly if both .ipynb and image lie on same place

[[0.998919   0.00108107]]
[[1. 0.]]


In [9]:
product

'Bad'